/*SAS/GRAPH software produces plots,charts, maps, and many of business and scientific graphics.*/
/*To create graphs with SAS/GRAPH you use procedures and other SAS/GRAPH statements to write programs.*/
/*example*/
proc print data=sashelp.class;
run;

proc gplot data=sashelp.class;
plot height*weight; /*gives the plot between the height and weight*/
run;

/*SASFILE graphs procedures
Charts/Plots: GAREABAR, GBARLINE, GCHART, GCONTOUR, GKPI, GPLOT, GRADAR, GTILE,G3D
Mapping:GEOCODE, GINSIDE, GMAP, GPROJECT, GREDUCE, GREMOVE, MAPIMPORT*/

proc sgplot data=sashelp.class;
scatter y=height x=weight; /*scatter plot with two variables specified x and y axis*/
run;

/*SAS can be used to generate these graphs*/
/* bar, block, pie, and star charts*/
/*two-dimensional scatter plots and line plots*/
/*three-dimensional scatter and surface plots*/
/*contour plots*/
/*maps*/
/*text slides*/
/*custom graphs*/

/*Generating the bar diagram with the sgplot*/

proc gchart data=sashelp.class;
title 'HBAR Bar Chart of sex'; /*Horizontal bar graph*/
hbar sex;
run;

/*Hence generated graph can be saved as desired format in the computer*/
ods pdf file='C:\Users\Owner\Desktop\SAS graph essentials\sanjay.pdf' ; /*generated pdf in the specific folder in the computer*/
proc gchart data=sashelp.class;
title 'VBAR Bar Chart of sex'; /*Vertical bar graph*/
vbar sex;
run;
ods pdf close;


proc gchart data=sashelp.class;
title 'HBAR Bar Chart of sex'; /*Horizontal bar graph*/
hbar sex;
run;                       /*statement run boundary*/
quit;                      /*step boundary*/



goptions ctext=blue ftext='Courier New/bold';/*go options global graphics solutions*/
proc gchart data=sashelp.class;
where age in (14, 15, 16);
title 'Bar Chart of age of student from age 14-16)';
hbar age/ name='sanjay';
run;
quit;
goptions reset=all; /*As final housekeeping, reset all GOPTIONS and global statements after program statements*/

/*goptions ctext=red reset=all;*/
/*goptions reset=all ctext=red;*/

/*RUN-Group Processing, SAS graph support run group processing for GPLOT, GCHART, GMAP,GSLIDE*/

proc gchart data=sashelp.class;
vbar age;
where age in (13, 14);
title 'Age group 13 and 14';
run;

vbar age;
where age in (15, 16);
title 'Age group 15 and 16';
run;
quit;


/*ODSDestination      DefaultStyle       Comments
LISTING             LISTING            White background, optimized for color format on white paper
HTML                HTMLBLUE           White background, optimized for HTML output
RTF                 RTF                White background, colored fills
PDF                 PRINTER            Optimized for PostScript and PDF output*/

/*What Styles Are Available? To display a list of available styles,submit the following:*/
proc template;
list styles;
run;



proc print data=sashelp.cars;
run;

goptions reset=all; 
proc gplot data=sashelp.cars; 
where Make= 'BMW' and origin= 'Europe';
plot MSRP * type; 
title 'BMW msrp'; 
run; 
quit;


goptions reset=all; 
symbol1 v=dot i=join;  /*joins the dots and give line display*/
proc gplot data=sashelp.cars; 
where Make= 'BMW' and origin= 'Europe';
plot MSRP * type; 
title 'BMW msrp'; 
run; 
quit;
title;


/*Producing Scatter and Line PlotsLine Plots*/

/*Creating Scatter Plots*/

proc gplot data=sashelp.cars;
plot origin * Msrp;        /*plot Y-axis * X-axis / options;*/
run;  
quit;

/*The SYMBOL statement defines the characteristics of symbols that display the data that is plotted by a PLOT statement*/

/*Option                       Purpose
VALUE=symbol
V=symbol                   Specifies the plot symbol to be used to represent plotted points.
CV=symbol-color            Specifies the color for the plot symbol.
HEIGHT=n units
H=n units                   Specifies the height of the plot symbol in CELLS (default), CM, IN, PT, or PCT*/


proc gplot data=sashelp.cars; 
where origin = 'Europe'; 
plot Make * msrp; 
plot drivetrain * length;
title 'make and msrp'; 
run; 
quit;


/*optimizing the symbols and color */
goptions reset=symbol;
symbol1 v=: cv=red h=2; 
symbol2 v=square cv=green h=1cm; 
symbol3 v="'" cv=blue h=.3in;
proc gplot data=sashelp.cars; 
where origin = 'Europe'; 
plot Make * msrp; 
plot drivetrain * length;
title 'make and msrp'; 
run; 
quit;


/*Creating Line Plots*/

symbol1 cv=blue value=star i=join;
proc gplot data=sashelp.cars;
plot msrp * Make;
run;
quit;

symbol1 cv=blue value=dot h=2 i= join ci=red line=2 w=2;
proc gplot data=sashelp.cars;
plot msrp * Make;
run;
quit;


/*line plots can be generated by Using the INTERPOL= option in the SYMBOL statement, generate line plots*/


goptions reset=symbol; 
symbol1 v=none w=3 l=2 ci=black i=spline; 
proc gplot data=Sashelp.cars; 
where origin = 'Europe'; 
plot msrp * Make; 
title 'INTERPOL = SPLINE'; 
run; 
quit;

/*interpol= none : no plot line be generated*/

goptions reset=symbol; 
symbol1 v=none w=3 l=2 ci=black i=none; 
proc gplot data=Sashelp.cars; 
where origin = 'Europe'; 
plot msrp * Make; 
title 'INTERPOL = SPLINE'; 
run; 
quit;

/*interpol=join: connects data points with a straight line*/



/*interpol=spline connects data with smoothed line*/


goptions reset=symbol; 
symbol1 v=none w=3 l=2 ci=black i=sm60; 
proc gplot data=Sashelp.cars; 
where origin = 'Europe'; 
plot msrp * Make; 
title 'INTERPOL = SPLINE'; 
run; 
quit;

/*Creating Plots Containing Multiple Lines*/


goptions reset=symbol; 
symbol1 v=dot color=orange i=join; 
symbol2 v=circle color='dark yellow' i=join;
proc gplot data=Sashelp.cars; 
where origin = 'Europe' and make= 'BMW'; 
plot drivetrain*msrp  model*msrp / overlay legend; 
title 'multiple lines'; 
run; 
quit;

/*Creating Other Types of Plots with Individual Data Pointsa Points*/

goptions reset=symbol; 
symbol1 v=dot color=orange i=join; 
symbol2 v=circle color='dark yellow' i=join; 
symbol3 color=black i=join;
proc gplot data=Sashelp.citiyr; 
plot pan*date pan17*date / overlay legend; 
plot2 pan18*date/legend;
title 'more plots'; 
run; 
quit;






/*Creating Other Types of Plots with Individual Data Points*/
/*Generate regression plots*/

/*Following additional interpolation methods can be specified in the SYMBOL statement:*/
/*interpol=rXXXXXXX-Generates a regression line that fits the data.xxxxxxx represents the type of regression, whether to force the line
                              through the plot origin, whether to display confidence limits, and the confidence levels.*/
/*interpol=needle - Draws a vertical line from each data point to the minimum value on the vertical axis or a horizontal line at the 0 value on the vertical axis.*/
/*stepxxx =Connects the data points with a step function, xxx represents where to place the data points, whether to join, with a vertical line, and whether to sort the data.*/


/*Regression Interpolation*/

goptions reset=symbol;
symbol1 v=square h=2 w=2 color=black co=green i=rlclm90; 
proc gplot data=sashelp.stocks; 
where stock = 'IBM' and year(date)=2005; 
plot open* date; 
title 'Regression Interpolation'; 
run; quit;


/*needle*/

goptions reset=symbol;
symbol1 v=square h=2 w=2 color=black co=green i=needle; 
proc gplot data=sashelp.stocks; 
where stock = 'IBM' and year(date)=2005; 
plot open* date; 
title 'Regression needle'; 
run; quit


/*steprj*/
goptions reset=symbol;
symbol1 v=square h=2 w=2 color=black co=green i=steprj; 
proc gplot data=sashelp.stocks; 
where stock = 'IBM' and year(date)=2005; 
plot open* date; 
title 'Regression Interpolation'; 
run; quit;

proc print data=sashelp.stocks; 
run;


/*'Using Two Symbol Statements to Control Sorting';*/

goptions reset=symbol; 
symbol1 v=diamond cv=red ci=blue h=2 i=stepcjs; 
symbol2 v=diamond cv=red ci=blue h=2 i=stepcj; 
proc gplot data=sashelp.stocks; 
where stock = 'IBM' and year(date)=2005;
plot open * date = 1; plot open* date = 2; 
title 'Using Two Symbol Statements to Control Sorting'; 
run; quit;



proc print data=sashelp.stocks; 
run;


/*producing bar charts*/
/**/
/*Creating Vertical Bar Charts*/

proc gchart data=sashelp.stocks;
title1 "open stock distribution"; 
vbar open; 
run; quit;

/*Creating Horizontal Bar Charts*/
proc gchart data=sashelp.stocks;
title1 "open stock distribution"; 
hbar open; 
run; quit;

/*Creating Multiple Multiple Vertical Bar Charts Vertical Bar Charts with Similar Attributeswith Similar Attributes*/


proc gchart data=sashelp.stocks; 
title1 "Distribution of open"; 
title2 "(Total open amount appears above each bar)";
vbar stock date / discrete type=mean sumvar=open freq patternid=midpoint; 
label open="Average open amount per stock"; 
format date year4. open dollar8.; run; quit;


/*SuppressingSuppressing Statistics Statistics in Horizontal Bar Chartsin Horizontal Bar Charts*/

proc gchart data=sashelp.stocks; 
title1 "Distribution of open per stock";
hbar stock/ range nostats; 
run; quit;


/*Controlling Midpoint Bars of Vertical Bar Charts*/

proc gchart data=sashelp.stocks; 
title1 "Distribution of open value"; 
vbar open / levels=5 outside=percent inside=freq; 
format open dollar4.; run; quit;


/*Creating 3--D D Horizontal Bar ChartHorizontal Bar Charts with s with Custom Statistic HeadingCustom Statistic Headings*/
proc gchart data=sashelp.stocks; 
title1 "yearly open stock report"; 
where year (date)=2005 and stock ='IBM';
/* SUMLABEL option alters statistic heading */ 
/* SHAPE=CYLINDER requests 3-D cylindrical bars */ 
/* ASCENDING requests longest bars at the top */ 
hbar3d date / discrete ascending sumvar=open sum sumlabel='Total open' shape=cylinder levels=all;
/* DESCENDING requests shortest bars at the top */ 
hbar3d date / discrete descending sumvar=open sum sumlabel='Order Count' shape=cylinder levels=all;
run; quit;

proc print data=sashelp.stocks; 
run;

/*Producing Other Types of Chartsof Charts*/

/*Creating Pie Charts*/

/*besides the horizontla and vertical charts, GCHART procedure creates horizontal and vertical bar charts*/




proc gchart data=sashelp.stocks; 
where year (date)=2005;
pie stock / clockwise ascending noheading sumvar=open type=sum percent=inside slice=arrow other=5;
title 'Pie chart per stock'; 
run; quit;


proc gchart data=sashelp.stocks; 
where stock='IBM';
pie date/ clockwise ascending noheading sumvar=open type=sum percent=inside slice=arrow other=5;
title 'open stock for year for IBM';
format date year4.; 
run; quit;

proc gchart data=sashelp.stocks; 
where stock='IBM';
pie date/ clockwise ascending noheading sumvar=open type=sum percent=inside slice=arrow other=5;
title 'open stock for month for IBM';
format date monname10.; 
run; quit;


proc format; 
value openfmt low -< 90 = 'Less than 90'
               90-< 100 = '90-100'
              100 - high = '100 or more'; 
			  run;


proc gchart data=sashelp.stocks; 
where stock='IBM';
pie stock / type=Percent detail=open detail_radius=85; 
format open openfmt.; 
title 'open stock'; 
run; 
quit;


/*Creating Donut Charts*/


proc gchart data=sashelp.stocks; 
where stock='IBM';
donut stock / discrete angle=-90 sumvar=open type=sum slice=arrow value=inside otherlabel='Other Levels';
title 'open stock with donuts'; 
run; 
quit;



/*Creating Star Charts*/

proc gchart data=sashelp.stocks;
star stock / sumvar=open type=sum noconnect;
title 'stock- Not Connected';
run;
quit;


proc gchart data=sashelp.stocks;
star stock / sumvar=open type=sum;
title 'stock-Connected';
run;
quit;

/*Creating Radar Charts */


proc gradar data=sashelp.stocks; 
chart stock; 
title 'Radar Chart for stock'; 
run; quit;


/*Creating Tile Charts*/

goptions device=activex;
proc gtile data=sashelp.stocks;
tile open /*The sum of the size variable determines the size of each tile, and the size variable is used to color each tile*/
tileby=(stock);
run;


/*Creating Key Performance Indicator Charts

SAS/GRAPH Colors
• RGB (red, green, blue) color values
• HLS (hue, lightness, saturation) values
• Gray-scale color names
• SAS color names (from the SAS Registry)
• SAS Color Naming System (CNS)
• CMYK (cyan magenta yellow black)
• HSV (hue saturation brightness)

RGB Color Codes
Use the RGB color-naming scheme to specify a color in terms of its red,
green, and blue components. Color names are of the form CXrrggbb, where
• CX indicates the RGB color specification
• rr is the red component
• gg is the green component
• bb is the blue component.
The components are given as hexadecimal characters in the range of 00
through FF. Most web page (HTML page) colors use RGB color values.



Hexadecimal Values Are Percentages
For example:
cxFF0000 = 100% red, 0% green, 0% blue
cx00FF00 = 0% red, 100% green, 0% blue
cx339966 = 20% red, 60% green, 40% blue





Selected Font Names
The following table shows some of the fonts that you can choose in your SAS program:
Category                                       Fonts
System fonts supplied with the
operating system (Windows)                    Arial, Courier New, Times New Roman
System fonts supplied with the
operating system (UNIX)                        Helvetica, Courier, Times
System fonts supplied by SAS                  Albany AMT, Cumberland AMT, Thorndale AMT
SAS/GRAPH software fonts                       Swiss, Special, Marker